# Component constraints for C:\Users\Lory\Desktop\PSoC-Final-Project\AY1920_II_HW_FINAL_CARZANIGA_GUALNIERA\AY1920_II_HW_FINAL_CARZANIGA_GUALNIERA.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Lory\Desktop\PSoC-Final-Project\AY1920_II_HW_FINAL_CARZANIGA_GUALNIERA\AY1920_II_HW_FINAL_CARZANIGA_GUALNIERA.cydsn\AY1920_II_HW_FINAL_CARZANIGA_GUALNIERA.cyprj
# Date: Sat, 23 May 2020 14:33:18 GMT
