/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "COUNT_CLOCK.h"
#include "BUTTON_CLOCK.h"
#include "ISR_CONFIG.h"
#include "PWM_CLOCK.h"
#include "PWM_RG.h"
#include "PWM_B.h"
#include "GREEN_PIN_aliases.h"
#include "GREEN_PIN.h"
#include "RED_PIN_aliases.h"
#include "RED_PIN.h"
#include "BLUE_PIN_aliases.h"
#include "BLUE_PIN.h"
#include "ISR_START.h"
#include "BUTTON_PIN_aliases.h"
#include "BUTTON_PIN.h"
#include "UART.h"
#include "TIMER_BUTTON.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "RX_PIN_aliases.h"
#include "RX_PIN.h"
#include "CS_aliases.h"
#include "CS.h"
#include "ONBOARD_LED_aliases.h"
#include "ONBOARD_LED.h"
#include "UART_IntClock.h"
#include "SPIM_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

